# Generated by Django 4.1.2 on 2022-11-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_blog', models.CharField(max_length=100)),
                ('construido_por', models.CharField(max_length=100)),
                ('titulo_principal', models.CharField(default='', max_length=100)),
                ('subtitulo_principal', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
